CREATE DATABASE `steamlug-bot`;
USE `steamlug-bot`;
CREATE TABLE `tweets` (tweet_id BIGINT UNSIGNED UNIQUE NOT NULL, tweet_date DATETIME NOT NULL, tweet_text VARCHAR(500) NOT NULL, tweet_user VARCHAR(500) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `settings` (setting_key VARCHAR(200) UNIQUE NOT NULL, setting_value VARCHAR(200) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `settings` VALUES ('last_tweet_mentioned', '0');
CREATE TABLE `log` (log_id BIGINT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT, log_nick VARCHAR(500) NOT NULL, log_ident VARCHAR(500) NOT NULL, log_host VARCHAR(500) NOT NULL, log_command VARCHAR(500) NOT NULL, log_channel VARCHAR(500), log_person VARCHAR(500), log_text VARCHAR(500), log_datetime DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
